name: Build Linux Frontend
on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies & Builder
        run: |
          cd electron-app/resources/app-unpacked
          npm install
          npm install --save-dev electron-builder

      - name: Build AppImage
        run: |
          cd electron-app/resources/app-unpacked
          npx electron-builder --linux AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nomi-Linux-AppImage
          path: dist/*.AppImage